---
version: 2
"$schema": https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

final_space: true
console_title_template: "{{if .Root}}(Admin){{end}} {{.PWD}}"

palette:
  bg-pink-400: "#F38BA8"
  bg-red-600: "#D70000"
  bg-red-700: "#AE1401"
  bg-yellow-200: "#FFFF66"
  bg-yellow-500: "#D7AF00"
  bg-yellow-600: "#87875F"
  bg-amber-500: "#FEAC19"
  bg-green-400: "#5FD700"
  bg-green-500: "#689f63"
  bg-teal-500: "#00AFAF"
  bg-teal-600: "#5F8787"
  bg-blue-300: "#88C0D0"
  bg-blue-500: "#4063D8"
  bg-cyan-500: "#00AFFF"
  bg-cyan-600: "#0087AF"
  bg-gray-300: "#d3d7cf"
  bg-stone-700: "#444444"

blocks:
- type: prompt
  alignment: left
  newline: true
  segments:
  - type: os
    foreground: p:bg-gray-300
    style: plain
    template: "{{.Icon}}{{ if .WSL }} {{ end }} "

  - type: git
    foreground: p:bg-green-400
    background: transparent
    style: plain
    properties:
      branch_ahead_icon: "<p:bg-blue-300>⇡</>"
      branch_behind_icon: "<p:bg-blue-300>⇣</>"
      branch_icon: " "
      branch_identical_icon: "≡ "
      branch_gone_icon: "≢ "
      branch_max_length: 25
      truncate_symbol: "…"
      commit_icon: " "
      tag_icon: " "
      rebase_icon: " "
      cherry_pick_icon: " "
      revert_icon: " "
      merge_icon: " "
      no_commits_icon: " "
      github_icon: " "
      gitlab_icon: " "
      bitbucket_icon: " "
      azure_devops_icon: " "
      codecommit_icon: " "
      codeberg_icon: " "
      git_icon: " "
      fetch_stash_count: true
      fetch_status: true
      fetch_upstream_icon: true
    template: >
      {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{
        end
      }}{{ if gt .StashCount 0 }}{{ if or (gt .Ahead 0) (gt .Behind 0) }} {{
        end
      }} {{ .StashCount }}{{
        end
      }}{{ if .Staging.Changed }} <p:bg-yellow-500></>{{
        end
      }}{{ if .Staging.Added }} <p:bg-green-400>+{{ .Staging.Added }}</>{{
        end
      }}{{ if .Staging.Modified }} <p:bg-yellow-500>~{{ .Staging.Modified }}</>{{
        end
      }}{{ if .Staging.Deleted }} <p:bg-pink-400>-{{ .Staging.Deleted }}</>{{
        end
      }}{{ if .Staging.Unmerged }} <p:bg-pink-400>x{{ .Staging.Unmerged }}</>{{
        end
      }}{{ if .Staging.Untracked }} <p:bg-cyan-500>?{{ .Staging.Untracked }}</>{{
        end
      }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{
        end
      }}{{ if .Working.Changed }} <p:bg-yellow-500></>{{
        end
      }}{{ if .Working.Added }} <p:bg-green-400>+{{ .Working.Added }}</>{{
        end
      }}{{ if .Working.Modified }} <p:bg-yellow-500>~{{ .Working.Modified }}</>{{
        end
      }}{{ if .Working.Deleted }} <p:bg-pink-400>-{{ .Working.Deleted }}</>{{
        end
      }}{{ if .Working.Unmerged }} <p:bg-pink-400>x{{ .Working.Unmerged }}</>{{
        end
      }}{{ if .Working.Untracked }} <p:bg-cyan-500>?{{ .Working.Untracked }}</>{{
        end
      }}{{ if true }} {{
        end
      }}

- type: prompt
  alignment: right
  filler: "<p:bg-stone-700>·</>"
  segments:
  - type: node
    foreground: p:bg-green-500
    background: transparent
    properties:
      fetch_version: true
    style: plain
    template: "  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}"
  - type: go
    foreground: p:bg-cyan-500
    background: transparent
    properties:
      fetch_version: true
    style: plain
    template: " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
  - type: julia
    foreground: p:bg-blue-500
    background: transparent
    properties:
      fetch_version: true
    style: plain
    template: "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
  - type: python
    foreground: p:bg-teal-500
    background: transparent
    properties:
      display_mode: files
      fetch_virtual_env: false
    style: plain
    template: "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ if .Venv }} {{ .Venv }}{{
      end }}{{ end }}"
  - foreground: p:bg-red-700
    background: transparent
    properties:
      display_mode: files
      fetch_version: true
    style: plain
    template: "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
    type: ruby
  - foreground: p:bg-amber-500
    background: transparent
    properties:
      display_mode: files
      fetch_version: false
    style: plain
    template: " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
    type: azfunc
  - background_templates:
    - '{{if contains "default" .Profile}}p:bg-amber-500{{end}}'
    - '{{if contains "jan" .Profile}}p:bg-red-700{{end}}'
    foreground: white
    background: transparent
    properties:
      display_default: false
    style: plain
    template: "  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }}"
    type: aws
  - foreground: p:bg-yellow-600
    background: transparent
    style: plain
    template: "  {{ .FormattedMs }}"
    type: executiontime
  - foreground: p:bg-red-600
    background: transparent
    properties:
      always_enabled: true
    style: plain
    template: "{{ if gt .Code 0 }} ✘ {{ .Meaning }} ({{ .Code }}){{ else }}{{ end }}"
    type: exit
  - foreground: p:bg-yellow-200
    background: transparent
    style: plain
    template: "  "
    type: root
  - foreground: p:bg-teal-600
    background: transparent
    style: plain
    template: "  {{ .CurrentDate | date .Format }} "
    type: time

- type: prompt
  alignment: left
  newline: true
  segments:
  - type: path
    foreground: p:bg-cyan-600
    background: transparent
    style: plain
    properties:
      style: full
    template: "{{ .Path }} "

- type: prompt
  alignment: left
  newline: true
  segments:
  - type: text
    foreground: p:bg-green-400
    background: transparent
    foreground_templates:
    - "{{ if gt .Code 0 }}p:bg-red-600{{ end }}"
    style: plain
    properties:
      always_enabled: true
    template: "❯"

transient_prompt:
  foreground: p:bg-green-400
  foreground_templates:
  - "{{ if gt .Code 0 }}p:bg-red-600{{ end }}"
  background: transparent
  template: "❯ "
