#!/usr/bin/env bash
# Transfer dotfiles from local host to remote using scp utility

# define users data
USER_0="awerebea"
EMAIL_0="awerebea.21@gmail.com"
USER_1="Andrei Bulgakov"
EMAIL_1="andrei_bulgakov1@epam.com"
USER_2="Andrei Bulgakov"
EMAIL_2="a.bulgakov.86@gmail.com"

GLOBAL=

# Usage message
usage () {
    local MESSAGE=
    read -r -d '' MESSAGE << __EOM__ || true
usage: ${0} [-g|--global] [USERNAME] [-h|--help]
Configure the git username and email address for the current git repository (default)
or globally for the current user.

USERNAME:
  0, awerebea       User data: ${USER_0} <${EMAIL_0}>

  1, work           User data: ${USER_1} <${EMAIL_1}>

  2, realname       User data: ${USER_2} <${EMAIL_2}>


  -h, --help
            Print this help message and exit
__EOM__
    echo "${MESSAGE}"
    return
}

# variables list
USERNAME=
USEREMAIL=

# Process command line options
while [[ -n "$1" ]]; do
    case "$1" in
    -g | --global)
        GLOBAL='global'
        ;;
    0 | awerebea)
        USERNAME="${USER_0}"
        USEREMAIL="${EMAIL_0}"
        ;;
    1 | work)
        USERNAME="${USER_1}"
        USEREMAIL="${EMAIL_1}"
        ;;
    2 | realname)
        USERNAME="${USER_2}"
        USEREMAIL="${EMAIL_2}"
        ;;
    -h | --help)
        usage
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
    shift
done

# check if all required arguments are specified
if [[ -z ${USERNAME} ]]; then
    usage
    exit 1;
fi


git config --${GLOBAL:-local} user.name "${USERNAME}"
git config --${GLOBAL:-local} user.email "${USEREMAIL}"

git config --list --show-origin | grep -e user.name -e user.email
