#!/usr/bin/env bash

[ $# -lt 1 ] && echo "Remote host is not specified." && return 1
copy-configs-over-ssh "$1"
ssh -t "$1" '(export ZSH_BIN_URL="https://raw.githubusercontent.com/romkatv/\
zsh-bin/master/install"; sh -c "$(curl -fsSL $ZSH_BIN_URL)" ||
sh -c "$(wget -O- $ZSH_BIN_URL)")'
