#! /bin/bash

for file in "$@"; do
  case "$file" in
      *.7z) 7z x "$file" ;;
      *.tar) tar -xvf "$file" ;;
      *.tar.bz2) tar -xjvf "$file" ;;
      *.tar.gz | *.tgz) tar -xzvf "$file" ;;
      *.zip) unzip "$file" ;;
      *) echo "Unsupported format" ;;
  esac
done
