return {
  {
    "mrjones2014/legendary.nvim",
    keys = {
      { "<S-M-p>", "<Cmd>Legendary<CR>", desc = "Legendary" },
      { "<leader>hc", "<Cmd>Legendary commands<CR>", desc = "Command Palette" },
    },
    opts = {
      which_key = { auto_register = true },
    },
  },
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    dependencies = { "echasnovski/mini.icons", "nvim-tree/nvim-web-devicons" },
    opts = {
      plugins = { spelling = { enabled = false } },
      win = { border = "single" },
      triggers = { "<auto>", mode = "nxsotc" },
    },
    keys = {
      {
        "<leader>?",
        function()
          require("which-key").show({ global = false })
        end,
        desc = "Buffer Local Keymaps (which-key)",
      },
    },
    config = function(_, opts)
      local wk = require("which-key")
      wk.setup(opts)
      wk.add({
        -- stylua: ignore
        {
          mode = { "n", "v" },
          { "<leader><space>", group = "Hop, Harpoon" },
          { "<leader><space>2", group = "Hop" },
          { "<leader>M", group = "Multiple Renamer (muren)" },
          { "<leader>S", group = "Spectre" },
          { "<leader>T", group = "Test" },
          { "<leader>Tn", group = "Neotest" },
          { "<leader>To", group = "Overseer" },
          { "<leader>Tt", group = "vim-test" },
          { "<leader>a", group = "AI" },
          { "<leader>b", group = "Buffer Reopen" },
          { "<leader>c", group = "Code, Copy path, CopilotChat" },
          { "<leader>cX", group = "Swap Previous" },
          { "<leader>cXc", group = "Class" },
          { "<leader>cXf", group = "Function" },
          { "<leader>cXp", group = "Parameter" },
          { "<leader>cc", group = "CopilotChat" },
          { "<leader>cch", group = "Help actions" },
          { "<leader>ccp", group = "Prompt actions" },
          { "<leader>cg", group = "neogen" },
          { "<leader>cp", group = "Copy path to clipboard" },
          { "<leader>cpd", group = "Directory" },
          { "<leader>cpf", group = "File" },
          { "<leader>cr", group = "refurb" },
          { "<leader>cri", "<cmd>cexpr system('refurb --quiet ' . shellescape(expand('%'))) | copen<cr>", desc = "Inspect" },
          { "<leader>cx", group = "Swap Next" },
          { "<leader>cxc", group = "Class" },
          { "<leader>cxf", group = "Function" },
          { "<leader>cxp", group = "Parameter" },
          { "<leader>d", group = "Debug" },
          { "<leader>f", group = "Find / Picker" },
          { "<leader>fa", group = "Additional" },
          { "<leader>fb", desc = "Buffers across all tabs" },
          { "<leader>fc", group = "Clipboard, Grep" },
          { "<leader>fS", group = "Symbols" },
          { "<leader>fT", desc = "Toggle fuzzy picker" },
          { "<leader>g", group = "Git, ChatGPT" },
          { "<leader>gb", group = "Git Branches" },
          { "<leader>gc", group = "Conflicts, Advanced Git search" },
          { "<leader>gcq", group = "Conflicts to quickfix list" },
          { "<leader>gcr", group = "Conflicts refresh" },
          { "<leader>gd", group = "DiffView" },
          { "<leader>gf", group = "Vim-Flog" },
          { "<leader>gl", group = "Git log" },
          { "<leader>gp", group = "ChatGPT" },
          { "<leader>gpr", group = "Run command" },
          { "<leader>gs", group = "Git status" },
          { "<leader>gw", group = "Git Worktree" },
          { "<leader>h", group = "Help, Grapple" },
          { "<leader>k", group = "Open from quickfix, Macrothis" },
          { "<leader>kk", group = "Macrothis" },
          { "<leader>l", group = "Toggle non-printable symbols" },
          { "<leader>n", group = "Navbuddy" },
          { "<leader>p", group = "Project" },
          { "<leader>q", group = "Session manager" },
          { "<leader>r", group = "Remove duplicates, Restart LSP, rename symbol" },
          { "<leader>s", group = "Spellcheck" },
          { "<leader>sc", group = "Spellcheck toggle" },
          { "<leader>.", group = "Scratch" },
          { "<leader>t", group = "Tabs / Toggle" },
          { "<leader>tN", group = "Neotest" },
          { "<leader>tt", group = "Toggle" },
          { "<leader>tg", group = "Toggle LSP" },
          { "<leader>tm", group = "Move tab" },
          { "<leader>to", group = "Overseer" },
          { "<leader>u", desc = "Toggle Undo-tree" },
          { "<leader>w", group = "Pick a window" },
          { "<leader>wl", group = "LSP workspace folders" },
          { "<leader>x", group = "Trouble, diagnostics" },
          { "<leader>/", group = "Search in buffer" },
          { "<localleader>d", group = "Diff actions" },
          -- {{{ Grapple
          { "<leader>ha", desc = "Grapple tag toggle" },
          { "<leader>hl", desc = "Grapple tags" },
          { "<leader>hL", desc = "Grapple scopes" },
          { "[h", desc = "Prev grapple tag" },
          { "]h", desc = "Next grapple tag" },
          -- }}}
        },
      })
    end,
  },
}
